post:
  tags:
    - config
  summary: Add identity provider
  parameters:
    - name: organizationID
      in: path
      required: true
      schema:
        type: string
        example: "{{company-id}}"
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../../../definitions/config/ConfigureExternalIdentityProviderRequest.yaml"
    required: true
  responses:
    "201":
      description: Created
      content:
        application/json:
          schema:
            $ref: "../../../../definitions/config/ConfigureExternalIdentityProviderResponse.yaml"
  deprecated: false
  security:
    - BearerAuth: []
put:
  tags:
    - config
  summary: Update identity provider
  parameters:
    - name: organizationID
      in: path
      required: true
      schema:
        type: string
        example: "{{company-id}}"
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../../../definitions/config/ConfigureExternalIdentityProviderRequest.yaml"
    required: true
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../../definitions/config/ConfigureExternalIdentityProviderResponse.yaml"
  deprecated: false
  security:
    - BearerAuth: []
delete:
  tags:
    - config
  summary: Delete identity provider
  parameters:
    - name: organizationID
      in: path
      required: true
      schema:
        type: string
        example: "{{company-id}}"
  responses:
    "204":
      description: No Content
      content: {}
  deprecated: false
  security:
    - BearerAuth: []
get:
  tags:
    - config
  summary: Get identity provider
  parameters:
    - name: organizationID
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../../definitions/config/ConfigureExternalIdentityProviderResponse.yaml"
  deprecated: false
  security:
    - BearerAuth: []
