delete:
  tags:
    - config
  description: Delete multiple data attributes
  parameters:
    - name: orgId
      in: path
      required: true
      schema:
        type: string
    - name: dataAgreementId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - Organization
            type: object
            properties:
              Organization:
                $ref: "../../../definitions/onboard/Organisation.yaml"
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
