get:
  tags:
    - config
  description: Get global policy configurations
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../../definitions/config/GlobalDataPolicyConfiguration.yaml"
  deprecated: false
  security:
    - BearerAuth: []
post:
  tags:
    - config
  description: Update global policy configurations
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../../../definitions/config/GlobalDataPolicyConfiguration.yaml"
    required: true
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: "../../../../definitions/config/GlobalDataPolicyConfiguration.yaml"
  deprecated: false
  security:
    - BearerAuth: []
