operationId: configListWebhooks
summary: Get all webhooks for an organisation
description: Get all webhooks for an organisation
tags:
  - config
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          type: array
          items:
            required:
              - ID
              - PayloadURL
              - Disabled
              - TimeStamp
              - IsLastDeliverySuccess
            type: object
            properties:
              ID:
                type: string
              PayloadURL:
                type: string
              Disabled:
                type: boolean
              TimeStamp:
                type: string
              IsLastDeliverySuccess:
                type: boolean
deprecated: false
security:
  - BearerAuth: []