description: LIST - Returns all the revisions for the data attribute
operationId: configListDataAttributeRevisions
parameters:
  - $ref: "../parameters/dataAttributeId.yaml"
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          properties:
            dataAttribute:
              $ref: ../definitions/DataAttribute.yaml
            revisions:
              type: array
              items:
                $ref: ../definitions/Revision.yaml
            pagination:
              $ref: "../definitions/Pagination.yaml"
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
summary: LIST - List all data attribute revisions
tags:
  - config
x-specification-crudl-model: Revision
x-specification-pii-or-sensitive: "False"
x-specification-scenario: ""
x-specification-usecase: UC-C-PIC-A-003
