operationId: configDeleteWebhook
summary: DELETE - Delete webhook
description: Delete webhook
tags:
  - config
parameters:
  - name: webhookId
    in: path
    required: true
    style: simple
    schema:
      type: string
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          type: object
          properties:
            webhook:
              $ref: "../definitions/Webhook.yaml"
deprecated: false
security:
  - BearerAuth: []