description: LIST - Fetch all data agreements
operationId: configListAgreement
parameters:
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          properties:
            dataAgreements:
              items:
                  $ref: ../definitions/DataAgreement.yaml
              type: array
            pagination:
              $ref: "../definitions/Pagination.yaml"
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
summary: LIST - List all data agreements
tags:
  - config
x-specification-crudl-model: DataAgreement
x-specification-pii-or-sensitive: "False"
x-specification-scenario: ""
x-specification-usecase: UC-C-PIC-A-003
