operationId: configPingWebhook
summary: Ping webhook
description: Ping webhook
tags:
  - config
parameters:
  - name: webhookId
    in: path
    required: true
    style: simple
    schema:
      type: string
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          type: object
          properties:
            webhookPing:
              $ref: "../definitions/WebhookPing.yaml"
deprecated: false
security:
  - BearerAuth: []
