operationId: configReadRecentWebhookDelivery
summary: Get recent webhook delivery by ID
description: Get recent webhook delivery by ID
tags:
  - config
parameters:
  - name: webhookId
    in: path
    required: true
    style: simple
    schema:
      type: string
  - name: deliveryId
    in: path
    required: true
    style: simple
    schema:
      type: string
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          required:
            - ID
            - RequestHeaders
            - RequestPayload
            - ResponseHeaders
            - ResponseBody
            - ResponseStatusCode
            - ResponseStatusStr
            - ExecutionStartTimeStamp
            - ExecutionEndTimeStamp
            - Status
            - StatusDescription
          type: object
          properties:
            ID:
              type: string
            RequestHeaders:
              required:
                - Accept
                - Content-Type
                - User-Agent
                - X-Igrant-Signature
              type: object
              properties:
                Accept:
                  type: array
                  items:
                    type: string
                Content-Type:
                  type: array
                  items:
                    type: string
                User-Agent:
                  type: array
                  items:
                    type: string
                X-Igrant-Signature:
                  type: array
                  items:
                    type: string
            RequestPayload:
              required:
                - data
                - deliveryid
                - timestamp
                - type
                - webhookid
              type: object
              properties:
                data:
                  required:
                    - attribute
                    - consentID
                    - days
                    - organisationID
                    - purposeID
                    - timestamp
                    - userID
                  type: object
                  properties:
                    attribute:
                      type: array
                      items:
                        type: string
                    consentID:
                      type: string
                    days:
                      type: integer
                      format: int32
                    organisationID:
                      type: string
                    purposeID:
                      type: string
                    timestamp:
                      type: string
                    userID:
                      type: string
                deliveryid:
                  type: string
                timestamp:
                  type: string
                type:
                  type: string
                webhookid:
                  type: string
            ResponseHeaders:
              ResponseHeaders: null
              title: ResponseHeaders
              required:
                - Cache-Control
                - Content-Type
                - Date
                - Server
                - Vary
                - X-Request-Id
                - X-Token-Id
              type: object
              properties:
                Cache-Control:
                  type: array
                  items:
                    type: string
                Content-Type:
                  type: array
                  items:
                    type: string
                Date:
                  type: array
                  items:
                    type: string
                Server:
                  type: array
                  items:
                    type: string
                Vary:
                  type: array
                  items:
                    type: string
                X-Request-Id:
                  type: array
                  items:
                    type: string
                X-Token-Id:
                  type: array
                  items:
                    type: string
            ResponseBody:
              type: string
            ResponseStatusCode:
              type: integer
              format: int32
            ResponseStatusStr:
              type: string
            ExecutionStartTimeStamp:
              type: string
            ExecutionEndTimeStamp:
              type: string
            Status:
              type: string
            StatusDescription:
              type: string
deprecated: false
security:
  - BearerAuth: []