operationId: configListWebhooks
summary: LIST - List all webhooks
description: Get all webhooks for an organisation
tags:
  - config
parameters:
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    description: OK
    content:
      application/json:
        schema:
          type: object
          properties:
            webhooks:
              type: array
              items:
                oneOf:
                  - $ref: "../definitions/Webhook.yaml"
                description: "Webhook"
            pagination:
              $ref: "../definitions/Pagination.yaml"
deprecated: false
security:
  - BearerAuth: []
