description: READ - fetches the latest version of a data agreement
operationId: configReadAgreement
parameters:
- description: Unique ID of an object
  in: path
  name: dataAgreementId
  required: true
  schema:
    type: string
responses:
  '200':
    content:
      application/json:
        schema:
          items:
            oneOf:
            - $ref: ../definitions/Agreement.yaml
            - $ref: ../definitions/Revision.yaml
          type: array
    description: ''
  '400':
    description: bad input parameter
security:
  - BearerAuth: []
summary: READ - fetches the latest version of a data agreement
tags:
- config
x-specification-crudl-model: Agreement
x-specification-pii-or-sensitive: 'False'
x-specification-scenario: ''
x-specification-usecase: UC-C-PIC-A-003
