operationId: configReadWebhookEventTypes
description: Get webhook event types
summary: LIST - List all webhook event types
tags:
  - config
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          required:
            - eventTypes
          type: object
          properties:
            eventTypes:
              type: array
              items:
                $ref: "../definitions/WebhookEventType.yaml"
deprecated: false
security:
  - BearerAuth: []