get:
  tags:
    - config
  description: Get data attribute by ID
  parameters:
    - name: organizationID
      in: path
      required: true
      schema:
        type: string
    - name: templateID
      in: path
      required: true
      schema:
        type: string
  responses:
    "201":
      description: Created
      content:
        application/json:
          schema:
            required:
              - OrgID
              - Template
            type: object
            properties:
              OrgID:
                type: string
              Template:
                $ref: "../../../definitions/config/DataAttribute.yaml"
  deprecated: false
  security:
    - BearerAuth: []
