post:
  tags:
    - config
  summary: Disable organization for subscription
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - Organization
            type: object
            properties:
              Organization:
                $ref: "../../../../definitions/onboarding/Organisation.yaml"
  deprecated: false
  security:
    - BearerAuth: []
