get:
  tags:
    - config
  summary: Get subscribe method
  parameters:
    - name: orgId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - ID
              - Method
            type: object
            properties:
              ID:
                type: integer
                format: int32
              Method:
                type: string
            example:
              ID: 1
              Method: Key-Based
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
post:
  tags:
    - config
  summary: Set subscribe method
  parameters:
    - name: orgId
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - subscribemethodid
          type: object
          properties:
            subscribemethodid:
              type: integer
              format: int32
          example:
            subscribemethodid: 1
    required: true
  responses:
    "204":
      description: No Content
      content: {}
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
