post:
  tags:
    - config
  summary: Renew subscribe key
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - SubscribeKey
              - SubscribeMethod
            type: object
            properties:
              SubscribeKey:
                type: string
              SubscribeMethod:
                type: string
            example:
              SubscribeKey: LDXM-9BJB-0DAS
              SubscribeMethod: Key-Based
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
