required:
  - authorizationUrl
  - tokenUrl
  - logoutUrl
  - clientAuthMethod
  - syncMode
  - clientId
  - clientSecret
  - jwksUrl
  - userInfoUrl
  - defaultScope
  - validateSignature
  - backchannelSupported
  - disableUserInfo
  - hideOnLoginPage
  - issuer
  - useJwksUrl
type: object
properties:
  authorizationUrl:
    type: string
  tokenUrl:
    type: string
  logoutUrl:
    type: string
  clientAuthMethod:
    type: string
  syncMode:
    type: string
  clientId:
    type: string
  clientSecret:
    type: string
  jwksUrl:
    type: string
  userInfoUrl:
    type: string
  defaultScope:
    type: string
  validateSignature:
    type: boolean
  backchannelSupported:
    type: boolean
  disableUserInfo:
    type: boolean
  hideOnLoginPage:
    type: boolean
  issuer:
    type: string
  useJwksUrl:
    type: boolean
example:
  authorizationUrl: https://iam.abc.io/auth
  tokenUrl: https://iam.abc.io/token
  logoutUrl: https://iam.abc.io/logout
  clientAuthMethod: client_secret_post
  syncMode: IMPORT
  clientId: idp-client
  clientSecret: 0654b48b-41c2-4887-ade5-fdb98d3fd13c
  jwksUrl: https://iam.abc.io/certs
  userInfoUrl: ""
  defaultScope: openid
  validateSignature: true
  backchannelSupported: true
  disableUserInfo: false
  hideOnLoginPage: true
  issuer: https://iam.abc.io
  useJwksUrl: true
