post:
  tags:
    - config
  description: Create webhook
  requestBody:
    content:
      application/json:
        schema:
          required:
            - payloadurl
            - subscribedevents
            - contenttype
            - secretkey
            - disabled
            - skipsslverification
          type: object
          properties:
            payloadurl:
              type: string
            subscribedevents:
              type: array
              items:
                type: string
            contenttype:
              type: string
            secretkey:
              type: string
            disabled:
              type: boolean
            skipsslverification:
              type: boolean
    required: true
  responses:
    "201":
      description: Created
      content:
        application/json:
          schema:
            required:
              - ID
              - OrgID
              - PayloadURL
              - ContentType
              - SubscribedEvents
              - Disabled
              - SecretKey
              - SkipSSLVerification
              - TimeStamp
            type: object
            properties:
              ID:
                type: string
              OrgID:
                type: string
              PayloadURL:
                type: string
              ContentType:
                type: string
              SubscribedEvents:
                type: array
                items:
                  type: string
              Disabled:
                type: boolean
              SecretKey:
                type: string
              SkipSSLVerification:
                type: boolean
              TimeStamp:
                type: string
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
get:
  tags:
    - config
  description: Get all webhooks for an organisation
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              required:
                - ID
                - PayloadURL
                - Disabled
                - TimeStamp
                - IsLastDeliverySuccess
              type: object
              properties:
                ID:
                  type: string
                PayloadURL:
                  type: string
                Disabled:
                  type: boolean
                TimeStamp:
                  type: string
                IsLastDeliverySuccess:
                  type: boolean
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
