get:
  tags:
    - config
  description: Get webhook event types
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - EventTypes
            type: object
            properties:
              EventTypes:
                type: array
                items:
                  type: string
            example:
              EventTypes:
                - data.update.initiated
                - data.update.cancelled
                - consent.allowed
                - consent.disallowed
                - consent.auto_expiry
                - org.unsubscribed
                - data.delete.initiated
                - data.download.initiated
                - data.delete.cancelled
                - data.download.cancelled
                - org.subscribed
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
