get:
  tags:
    - config
  description: Get webhook payload content types
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - ContentTypes
            type: object
            properties:
              ContentTypes:
                type: array
                items:
                  type: string
            example:
              ContentTypes:
                - application/json
                - application/x-www-form-urlencoded
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
