delete:
  tags:
    - config
  summary: Delete user from organization
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
    - name: userId
      in: path
      required: true
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - User
            type: object
            properties:
              User:
                $ref: "../../../definitions/onboarding/Individual.yaml"
  deprecated: false
  security:
    - BearerAuth: []
