required:
  - authorizationUrl
  - tokenUrl
  - logoutUrl
  - clientId
  - clientSecret
  - jwksUrl
  - validateSignature
  - disableuserinfo
  - issuer
  - defaultscope
type: object
properties:
  authorizationUrl:
    type: string
  tokenUrl:
    type: string
  logoutUrl:
    type: string
  clientId:
    type: string
  clientSecret:
    type: string
  jwksUrl:
    type: string
  validateSignature:
    type: boolean
  disableuserinfo:
    type: boolean
  issuer:
    type: string
  defaultscope:
    type: string
example:
  authorizationUrl: https://iam.abc.io/auth
  tokenUrl: https://iam.abc.io/token
  logoutUrl: https://iam.abc.io/logout
  clientId: idp-client
  clientSecret: 0654b48b-41c2-4887-ade5-fdb98d3fd13c
  jwksUrl: https://iam.abc.io/certs
  validateSignature: true
  disableuserinfo: false
  issuer: https://iam.abc.io
  defaultscope: openid
