get:
  tags:
    - config
  description: Get a webhook by ID
  parameters:
    - name: organizationId
      in: path
      required: true
      style: simple
      schema:
        type: string
    - name: webhookId
      in: path
      required: true
      style: simple
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - ID
              - OrgID
              - PayloadURL
              - ContentType
              - SubscribedEvents
              - Disabled
              - SecretKey
              - SkipSSLVerification
              - TimeStamp
            type: object
            properties:
              ID:
                type: string
              OrgID:
                type: string
              PayloadURL:
                type: string
              ContentType:
                type: string
              SubscribedEvents:
                type: array
                items:
                  type: string
              Disabled:
                type: boolean
              SecretKey:
                type: string
              SkipSSLVerification:
                type: boolean
              TimeStamp:
                type: string
  deprecated: false
  security:
    - BearerAuth: []
delete:
  tags:
    - config
  description: Delete webhook
  parameters:
    - name: organizationId
      in: path
      required: true
      style: simple
      schema:
        type: string
    - name: webhookId
      in: path
      required: true
      style: simple
      schema:
        type: string
  responses:
    "204":
      description: No Content
      content: {}
  deprecated: false
  security:
    - BearerAuth: []
put:
  tags:
    - config
  description: Update webhook
  parameters:
    - name: organizationId
      in: path
      required: true
      style: simple
      schema:
        type: string
    - name: webhookId
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - payloadurl
            - subscribedevents
            - contenttype
            - secretkey
            - disabled
            - skipsslverification
          type: object
          properties:
            payloadurl:
              type: string
            subscribedevents:
              type: array
              items:
                type: string

            contenttype:
              type: string
            secretkey:
              type: string
            disabled:
              type: boolean
            skipsslverification:
              type: boolean
    required: true
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - ID
              - OrgID
              - PayloadURL
              - ContentType
              - SubscribedEvents
              - Disabled
              - SecretKey
              - SkipSSLVerification
              - TimeStamp
            type: object
            properties:
              ID:
                type: string
              OrgID:
                type: string
              PayloadURL:
                type: string
              ContentType:
                type: string
              SubscribedEvents:
                type: array
                items:
                  type: string
              Disabled:
                type: boolean
              SecretKey:
                type: string
              SkipSSLVerification:
                type: boolean
              TimeStamp:
                type: string
  deprecated: false
  security:
    - BearerAuth: []
