post:
  tags:
    - config
  description: Ping webhook
  parameters:
    - name: orgId
      in: path
      required: true
      style: simple
      schema:
        type: string
    - name: webhookId
      in: path
      required: true
      style: simple
      schema:
        type: string
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            required:
              - ResponseStatusCode
              - ResponseStatusStr
              - ExecutionStartTimeStamp
              - ExecutionEndTimeStamp
              - Status
              - StatusDescription
            type: object
            properties:
              ResponseStatusCode:
                type: integer
                format: int32
              ResponseStatusStr:
                type: string
              ExecutionStartTimeStamp:
                type: string
              ExecutionEndTimeStamp:
                type: string
              Status:
                type: string
              StatusDescription:
                type: string
  deprecated: false
  security:
    - BearerAuth: []
  x-badges:
    - color: primary-color  # <<< Allowed values (red, green, orange, blue, primary-color)
      label: 'Authorised roles: Organisation admin'
