summary: UPDATE - Update data agreement
description: 
  This endpoint allows the admin to update the latest data agreement defined
  earlier in an organisation. It also returns the updated revision number.
operationId: configUpdateAgreement
parameters:
- description: Unique ID of an object
  in: path
  name: dataAgreementId
  required: true
  schema:
    type: string
requestBody:
  content:
    application/json:
      schema:
        properties:
          dataAgreement:
            $ref: ../definitions/DataAgreement.yaml
            description: An object of type DataAgreement
        required:
        - dataAgreement
        type: object
responses:
  '200':
    content:
      application/json:
        schema:
          type: object
          properties:
            dataAgreement:
              $ref: ../definitions/DataAgreement.yaml
            revision:
              $ref: ../definitions/Revision.yaml
    description: ''
  '400':
    description: bad input parameter
security:
  - BearerAuth: []

tags:
- config
