summary: READ - Read individual
description: 
  This endpoint is used to read an individual info defined for an 
  organisation in the consent building block.
operationId: "configReadIndividual"
parameters:
  - in: path
    name: "individualId"
    description: "Unique ID of an object"
    required: true
    schema:
      type: string
responses:
  "200":
    description: ""

    content:
      application/json:
        schema:
          type: object
          properties:
            individual:
              allOf:
                - $ref: "../definitions/Individual.yaml"
                - $ref: "../definitions/IndividualExtras.yaml"
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config