summary: LIST - List all individuals
description: 
  This endpoint is used to list all individuals in the organisation 
  defined in the consent building block.
operationId: "configListIndividuals"
parameters:
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    description: ""

    content:
      application/json:
        schema:
          type: object
          properties:
            individuals:
              type: array
              items:
                allOf:
                  - $ref: "../definitions/Individual.yaml"
                  - $ref: "../definitions/IndividualExtras.yaml"
            pagination:
              $ref: "../definitions/Pagination.yaml"
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config