description: CREATE - Create an API key
operationId: configCreateApikey
parameters: []
requestBody:
  content:
    application/json:
      schema:
        properties:
          apiKey:
            $ref: ../definitions/ApiKey.yaml
            description: An object of type ApiKey
        required:
        - apiKey
        type: object
responses:
  '200':
    content:
      application/json:
        schema:
          type: object
          properties:
            apiKey:
              $ref: ../definitions/ApiKey.yaml
    description: A set consisting of the new ApiKey object created, together with
      the initial Revision object.
  '400':
    description: bad input parameter
security:
  - BearerAuth: []
summary: CREATE - Create an API key
tags:
- config
x-specification-crudl-model: ApiKey
x-specification-pii-or-sensitive: 'False'
x-specification-scenario: ''
x-specification-usecase: UC-C-PIC-A-001
