summary: UPDATE - Update IDP
description: UPDATE - Update an IDP
operationId: configUpdatePolicy
parameters:
  - $ref: "../parameters/idpId.yaml"
requestBody:
  content:
    application/json:
      schema:
        properties:
          idp:
            $ref: ../definitions/IDP.yaml
            description: An object of type IDP
        required:
          - idp
        type: object
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          properties:
            idp:
              $ref: ../definitions/IDP.yaml
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config
x-specification-crudl-model: IDP
x-specification-pii-or-sensitive: "False"
x-specification-scenario: ""
x-specification-usecase: UC-C-PIC-A-002
