summary: LIST - List data agreement revisions
description:
  This endpoint lists all revisions of a data agreement defined earlier in an organisation.
operationId: configListAgreementRevisions
parameters:
  - $ref: "../parameters/dataAgreementId.yaml"
  - $ref: "../parameters/offset.yaml"
  - $ref: "../parameters/limit.yaml"
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          properties:
            dataAgreement:
              $ref: ../definitions/DataAgreement.yaml
            revisions:
              type: array
              items:
                $ref: ../definitions/Revision.yaml
            pagination:
              $ref: "../definitions/Pagination.yaml"
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config
x-specification-crudl-model: Revision
x-specification-pii-or-sensitive: "False"
x-specification-scenario: ""