summary: Re-deliver a webhook event
description: 
  This endpoint is used to re-deliver a webhook payload by delivery ID.
operationId: configRedeliverWebhook
parameters:
  - name: organizationId
    in: path
    required: true
    style: simple
    schema:
      type: string
  - name: webhookId
    in: path
    required: true
    style: simple
    schema:
      type: string
  - name: deliveryId
    in: path
    required: true
    style: simple
    schema:
      type: string
responses:
  "204":
    description: OK
    content: {}
deprecated: false
security:
  - BearerAuth: []
tags:
  - config
