summary: CREATE - Create IDP
description: 
  This endpoint is used to configure an IdP (e.g. OIDC based) used by 
  the organisation in the consent building block.
operationId: configCreateIdp
parameters: []
requestBody:
  content:
    application/json:
      schema:
        properties:
          idp:
            $ref: ../definitions/IDP.yaml
            description: An object of type IDP
        required:
          - idp
        type: object
responses:
  "200":
    content:
      application/json:
        schema:
          type: object
          properties:
            idp:
              $ref: ../definitions/IDP.yaml
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config