summary: READ - Read webhook event types
description: 
  This endpoint is used to list all webhook event types defined in 
  the consent building block.
operationId: configReadWebhookEventTypes
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          required:
            - eventTypes
          type: object
          properties:
            eventTypes:
              type: array
              items:
                $ref: "../definitions/WebhookEventType.yaml"
deprecated: false
security:
  - BearerAuth: []
tags:
  - config