summary: CREATE - Create individual
description: 
  This endpoint creates an individual for an organisation in the 
  consent block system. This is used to onboard existing or new users.
operationId: "configCreatePolicy"
responses:
  "200":
    description: ""
    content:
      application/json:
        schema:
          type: object
          properties:
            individual:
              allOf:
                - $ref: "../definitions/Individual.yaml"
                - $ref: "../definitions/IndividualExtras.yaml"
              description: An object of type Individual

  "400":
    description: bad input parameter
security:
  - BearerAuth: []
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          individual:
            allOf:
              - $ref: "../definitions/Individual.yaml"
              - $ref: "../definitions/IndividualExtras.yaml"
            description: An object of type Individual
        required:
          - individual
tags:
  - config
