description: READ - Fetch the latest version of a data agreement
operationId: configReadAgreement
parameters:
- description: Unique ID of an object
  in: path
  name: dataAgreementId
  required: true
  schema:
    type: string
responses:
  '200':
    content:
      application/json:
        schema:
          type: object
          properties:
            dataAgreement:
              $ref: ../definitions/DataAgreement.yaml
            revision:
              $ref: ../definitions/Revision.yaml
    description: ''
  '400':
    description: bad input parameter
security:
  - BearerAuth: []
summary: READ - Read data agreement
tags:
- config
x-specification-crudl-model: DataAgreement
x-specification-pii-or-sensitive: 'False'
x-specification-scenario: ''
x-specification-usecase: UC-C-PIC-A-003
