summary: DELETE - Delete API key
description: 
  This endpoint is used to delete an existing API key for  accessing 
  endpoints in the consent building block.
operationId: configDeletePolicy
parameters:
  - $ref: "../parameters/apiKeyId.yaml"
responses:
  "200":
    content:
      application/json:
        schema:
          allOf:
            - $ref: ../definitions/ApiKey.yaml
            - $ref: "../definitions/ApiKeyExtras.yaml"
    description: ""
  "400":
    description: bad input parameter
security:
  - BearerAuth: []
tags:
  - config
x-specification-crudl-model: ApiK
