required:
  - consent
  - description
  - purposeids
type: object
properties:
  consent:
    type: string
  description:
    type: string
  purposeids:
    type: array
    items:
      type: string
example:
  consent: Age
  description: example
  purposeids:
    - 64ecf184e2f6a8000142c678
