title: Data agreement
type: object
properties:
  language:
    type: string
  version:
    type: string
  dataControllerName:
    type: string
  dataControllerUrl:
    type: string
  dataPolicy:
    $ref: "./GlobalDataPolicyConfiguration.yaml"
  purpose:
    type: string
  purposeDescription:
    type: string
  lawfulBasis:
    type: string
  methodOfUse:
    type: string
  dpia:
    type: object
    properties:
      dpiaDate:
        type: string
      dpiaSummaryUrl:
        type: string
    required:
      - dpiaDate
      - dpiaSummaryUrl
  isPublished:
    type: boolean
  proof:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      created:
        type: string
      verificationMethod:
        type: string
      proofPurpose:
        type: string
      proofValue:
        type: string
    required:
      - id
      - type
      - created
      - verificationMethod
      - proofPurpose
      - proofValue
required:
  - language
  - version
  - dataControllerName
  - dataControllerUrl
  - dataPolicy
  - purpose
  - purposeDescription
  - lawfulBasis
  - methodOfUse
  - dpia
  - dataSubjectDid
  - proof
  - isPublished
