title: Data Attribute
type: object
properties:
  attributeId:
    type: string
  attributeName:
    type: string
  attributeSensitive:
    type: boolean
  attributeCategory:
    type: string
  attributeDescription:
    type: string
  dataAgreementIds:
    type: array
    items:
      type: string
required:
  - attributeId
  - attributeName
  - attributeSensitive
  - attributeCategory
  - attributeDescription
