title: Data agreement
type: object
properties:
  language:
    type: string
  version:
    type: string
  dataControllerName:
    type: string
  dataControllerUrl:
    type: string
  dataPolicy:
    $ref: "./GlobalDataPolicyConfiguration.yaml"
  purpose:
    type: string
  purposeDescription:
    type: string
  lawfulBasis:
    type: string
  methodOfUse:
    type: string
  dataAttributes:
    type: array
    items:
      $ref: "./DataAttribute.yaml"
  dpia:
    type: object
    properties:
      dpiaDate:
        type: string
      dpiaSummaryUrl:
        type: string
    required:
      - dpiaDate
      - dpiaSummaryUrl
  isPublished:
    type: boolean
  proof:
    $ref: "./Signature.yaml"
required:
  - language
  - version
  - dataControllerName
  - dataControllerUrl
  - dataPolicy
  - purpose
  - purposeDescription
  - lawfulBasis
  - methodOfUse
  - dpia
  - dataSubjectDid
  - proof
  - isPublished
