title: Data agreement
type: object
description: |
  The Data Agreement Vocabulary provides terms to describe and represent information related to 
  processing of personal data based on established requirements such as for the EU General Data 
  Protection Regulation (GDPR).
properties:
  language:
    type: string
    description: Language code for e.g. en-gb
  version:
    type: string
    description: Version number of the data agreement
  dataControllerName:
    type: string
    description: An organisation constituted as a legally defined entity in any jurisdiction.
  dataControllerUrl:
    type: string
    description: Organisation or data controller URL.
  dataPolicy:
    description: Encapsulate the data policies used in the use of personal data.
    $ref: "./GlobalDataPolicyConfiguration.yaml"
  purpose:
    description: |
      Describes the purpose for which a data controller (Data Source or Data Using Service) uses personal data for. 
      This is also the purpose for which the data agreeent is being formulated
    type: string
  purposeDescription:
    description: |
      Provides description of the purpose for which the personal data us used, 
      comprehensive to the individual whose data is being used by the data controller.
    type: string
  lawfulBasis:
    description: |
      An organization processing personal data to have a valid lawful basis for that personal data processing activity. GDPR, 
      for e.g., consent, legal_obligation, contract, vital_interest, public_task and legitimate_interest.
    type: string
  methodOfUse:
    description: |
      This is used to describe whether controller is using personal data for internal purposes of for data exchange towards an external third party. 
      Data exchange could be for exposing data (as a Data Source) or consuming data as a Data Using Service.
    type: string
  dataAttributes:
    description: |
      Encapsulates the attributes used for the the usage purpose defined. 
      Its an array of personal data attributes.
    type: array
    items:
      $ref: "./DataAttribute.yaml"
  dpia:
    description: Encapsulate the organisation performing the Data Protection Impact Assessment
    type: object
    properties:
      dpiaDate:
        description: The date on which the DPIA report is generated after a DPIA.
        type: string
      dpiaSummaryUrl:
        description: |
          The URl providing the DPIA result reports, summary etc that can be verified by any interested parties.
        type: string
    required:
      - dpiaDate
      - dpiaSummaryUrl
  isPublished:
    description: Is the data agreement published towards individuals or not
    type: boolean
  proof:
    $ref: "./Signature.yaml"
required:
  - language
  - version
  - dataControllerName
  - dataControllerUrl
  - dataPolicy
  - purpose
  - purposeDescription
  - lawfulBasis
  - methodOfUse
  - dpia
  - dataSubjectDid
  - proof
  - isPublished
