type: object
description: Digital signature to secure the integrity of the consent agreement
properties:
  id:
    type: string
    description: Identifier of the proof
  type:
    type: string
  created:
    description: Type of the proof
    type: string
  verificationMethod:
    description: Method of verification for the proof
    type: string
  proofPurpose:
    description: Purpose of the proof
    type: string
  proofValue:
    description: Value of the proof (Signature digest)
    type: string
required:
  - id
  - type
  - created
  - verificationMethod
  - proofPurpose
  - proofValue
