post:
  tags:
    - config
  description: Add consent agreement
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - purposes
          type: object
          properties:
            purposes:
              type: array
              items:
                $ref: "../../../definitions/config/ConsentAgreement.yaml"
    required: true
  responses:
    "201":
      description: Created
      content:
        application/json:
          schema:
            required:
              - Organization
            type: object
            properties:
              Organization:
                $ref: "../../../definitions/onboarding/Organisation.yaml"
  deprecated: false
  security:
    - BearerAuth: []
get:
  tags:
    - config
  description: Get consent agreements
  parameters:
    - name: organizationId
      in: path
      required: true
      schema:
        type: string
  responses:
    "201":
      description: Created
      content:
        application/json:
          schema:
            required:
              - OrgID
              - Purposes
            type: object
            properties:
              OrgID:
                type: string
              Purposes:
                type: array
                items:
                  $ref: "../../../definitions/config/ConsentAgreement.yaml"
  deprecated: false
  security:
    - BearerAuth: []
